use super::{
    CapturedCurrent, FIXTURE_CONTRACT_VERSION, FixtureSet, InventoryUnit, Rule, RuleStatus,
    Severity, Stage, Threshold,
};

pub const CHECKERS_SHIPPED: bool = false;

const fn count(value: u32, unit: InventoryUnit) -> CapturedCurrent {
    CapturedCurrent::Count { value, unit }
}

const fn thr(
    key: &'static str,
    default: Option<&'static str>,
    research_required: bool,
    notes: &'static str,
) -> Threshold {
    Threshold {
        key,
        default,
        research_required,
        notes,
    }
}

macro_rules! rule {
    (
        $id:expr,
        $captured_label:expr,
        $severity:expr,
        $unit:expr,
        $stage:expr,
        $evidence:expr,
        $applicability:expr,
        $threshold:expr,
        $references:expr,
        $owner_issues:expr,
        $status:expr,
        $captured_current:expr,
        $ambiguous:expr,
        $notes:expr,
        $positive:expr,
        $negative:expr,
        $incomplete:expr $(,)?
    ) => {
        Rule {
            id: $id,
            captured_label: $captured_label,
            severity: $severity,
            unit: $unit,
            stage: $stage,
            evidence: $evidence,
            applicability: $applicability,
            threshold: $threshold,
            references: $references,
            owner_issues: $owner_issues,
            status: $status,
            captured_current: $captured_current,
            ambiguous: $ambiguous,
            notes: $notes,
            fixtures: FixtureSet {
                version: FIXTURE_CONTRACT_VERSION,
                positive: $positive,
                negative: $negative,
                incomplete: $incomplete,
            },
        }
    };
}

const MDN_META: &str = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta";
const MDN_TITLE: &str = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title";
const MDN_VIEWPORT: &str = "https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag";
const RFC_9110: &str = "https://www.rfc-editor.org/rfc/rfc9110";
const RFC_9309: &str = "https://www.rfc-editor.org/rfc/rfc9309";
const SITEMAPS: &str = "https://www.sitemaps.org/protocol.html";
const GOOGLE_CANONICAL: &str =
    "https://developers.google.com/search/docs/crawling-indexing/canonicalization";
const GOOGLE_ROBOTS: &str =
    "https://developers.google.com/search/docs/crawling-indexing/robots/intro";
const GOOGLE_HREFLANG: &str =
    "https://developers.google.com/search/docs/specialty/international/localized-versions";
const MIXED_CONTENT: &str = "https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content";
const RFC_6797: &str = "https://www.rfc-editor.org/rfc/rfc6797";
const SCHEMA_ORG: &str = "https://schema.org/docs/gs.html";
const LLMS_TXT: &str = "https://llmstxt.org/";

pub const RULES: &[Rule] = &[
    rule!(
        "meta.duplicate_description",
        "Duplicate meta descriptions",
        Severity::Error,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "meta_description"],
        "Crawled HTML pages",
        thr(
            "normalized_exact_match",
            Some("trim and collapse whitespace"),
            false,
            "Exact duplicate after normalization. Not a Semrush formula.",
        ),
        &[MDN_META],
        &["TC-458"],
        RuleStatus::Specified,
        count(5, InventoryUnit::Page),
        false,
        "Current 14 September 2026 baseline finding.",
        "https://audit.example/a and https://audit.example/b share a normalized description",
        "https://audit.example/a and https://audit.example/b have unique descriptions",
        "https://audit.example/a returned 200 without a stored HTML body",
    ),
    rule!(
        "crawl.http_5xx",
        "HTTP 5xx",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Crawl,
        &["http_status"],
        "Fetched pages",
        thr(
            "status_class",
            Some("500-599"),
            false,
            "RFC 9110 server error class.",
        ),
        &[RFC_9110],
        &["TC-452", "TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/fail returns HTTP 500",
        "https://audit.example/ok returns HTTP 200",
        "https://audit.example/timeout produced no HTTP status",
    ),
    rule!(
        "crawl.http_4xx",
        "HTTP 4xx",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Crawl,
        &["http_status"],
        "Fetched pages treated as HTML documents",
        thr(
            "status_class",
            Some("400-499"),
            false,
            "RFC 9110 client error class.",
        ),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/missing returns HTTP 404",
        "https://audit.example/ok returns HTTP 200",
        "https://audit.example/dropped produced no HTTP status",
    ),
    rule!(
        "meta.missing_title",
        "Missing title",
        Severity::Error,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "title"],
        "Crawled HTML pages",
        thr(
            "presence",
            Some("non-empty title"),
            false,
            "Empty or absent <title>.",
        ),
        &[MDN_TITLE],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/untitled has no title element",
        "https://audit.example/titled has a non-empty title",
        "https://audit.example/partial HTML was truncated before </head>",
    ),
    rule!(
        "meta.duplicate_title",
        "Duplicate titles",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::HtmlMetadata,
        &["html", "title"],
        "Crawled HTML pages",
        thr(
            "normalized_exact_match",
            Some("trim and collapse whitespace"),
            false,
            "Exact duplicate after normalization. Unit is issues, not pages.",
        ),
        &[MDN_TITLE],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/a and https://audit.example/b share a normalized title",
        "https://audit.example/a and https://audit.example/b have unique titles",
        "https://audit.example/a title cannot be parsed from stored bytes",
    ),
    rule!(
        "content.duplicate",
        "Duplicate content",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Content,
        &["html", "text_extract", "simhash_or_exact_hash"],
        "Crawled HTML pages",
        thr(
            "exact_or_near_duplicate",
            None,
            true,
            "Exact vs near-duplicate threshold is owned by TC-466. Do not infer a private formula.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/canonicalization"],
        &["TC-466"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/copy-a and https://audit.example/copy-b have identical main text",
        "https://audit.example/a and https://audit.example/b have distinct main text",
        "https://audit.example/copy-a has no extracted text",
    ),
    rule!(
        "links.broken_internal",
        "Broken internal links",
        Severity::Error,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_href", "target_http_status", "origin"],
        "Same-origin <a href> targets discovered in HTML",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "Internal target fetch failed.",
        ),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from links internally to https://audit.example/missing (404)",
        "https://audit.example/from links internally to https://audit.example/ok (200)",
        "https://audit.example/from was parsed but the internal target was not fetched",
    ),
    rule!(
        "crawl.page_uncrawlable",
        "Page could not be crawled",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Crawl,
        &["fetch_error"],
        "Queued in-scope URLs",
        thr(
            "uncrawlable",
            Some("no usable HTTP response"),
            false,
            "Transport or protocol failure.",
        ),
        &[RFC_9110],
        &["TC-452"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/blocked resets the TCP connection",
        "https://audit.example/ok returns HTTP 200 HTML",
        "https://audit.example/queued has no fetch attempt recorded",
    ),
    rule!(
        "crawl.dns_failure",
        "DNS resolution failure",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Crawl,
        &["dns_error"],
        "Queued in-scope URLs",
        thr(
            "dns",
            Some("resolution failed"),
            false,
            "Name resolution error.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc1035"],
        &["TC-452"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://missing.audit.example/ cannot be resolved",
        "https://audit.example/ resolves and is fetched",
        "https://audit.example/pending has no DNS result stored",
    ),
    rule!(
        "url.incorrect_format",
        "Incorrect page URL format",
        Severity::Error,
        InventoryUnit::Page,
        Stage::UrlIdentity,
        &["url"],
        "Discovered page URLs",
        thr(
            "url_parse",
            Some("invalid per WHATWG URL parser"),
            false,
            "Malformed page URL, not a style preference.",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-451"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/bad url with spaces is not a valid URL",
        "https://audit.example/ok is a valid HTTPS URL",
        "https://audit.example/raw-href has no recorded raw href bytes",
    ),
    rule!(
        "images.broken_internal",
        "Broken internal images",
        Severity::Error,
        InventoryUnit::Image,
        Stage::Images,
        &["img_src", "resource_http_status", "origin"],
        "Same-origin img resources",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "Internal image fetch failed.",
        ),
        &[RFC_9110],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Image),
        false,
        "",
        "https://audit.example/page references https://audit.example/gone.png (404)",
        "https://audit.example/page references https://audit.example/ok.png (200)",
        "https://audit.example/page img src was extracted but not fetched",
    ),
    rule!(
        "robots.format_errors",
        "Robots format errors",
        Severity::Error,
        InventoryUnit::Site,
        Stage::Robots,
        &["robots_txt"],
        "Origin robots.txt",
        thr(
            "robots_syntax",
            Some("parse error"),
            false,
            "No-count site check; not a live failure.",
        ),
        &[RFC_9309, GOOGLE_ROBOTS],
        &["TC-450", "TC-460"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "https://audit.example/robots.txt contains an unknown malformed directive line",
        "https://audit.example/robots.txt parses with allow/disallow records",
        "https://audit.example/robots.txt body was not stored",
    ),
    rule!(
        "sitemap.format_errors",
        "Sitemap format errors",
        Severity::Error,
        InventoryUnit::File,
        Stage::Sitemap,
        &["sitemap_xml"],
        "Discovered sitemap files",
        thr(
            "sitemap_xml",
            Some("invalid sitemap XML"),
            false,
            "sitemaps.org XML validity.",
        ),
        &[SITEMAPS],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::File),
        false,
        "",
        "https://audit.example/sitemap.xml is not well-formed XML",
        "https://audit.example/sitemap.xml is a valid urlset",
        "https://audit.example/sitemap.xml was listed but not fetched",
    ),
    rule!(
        "sitemap.incorrect_pages",
        "Incorrect sitemap pages",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Sitemap,
        &["sitemap_url", "page_http_status", "canonical"],
        "URLs listed in sitemaps",
        thr(
            "sitemap_url_validity",
            None,
            true,
            "Which mismatches count (404, off-canonical, excluded) is owned by TC-460.",
        ),
        &[SITEMAPS, GOOGLE_CANONICAL],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/sitemap.xml lists https://audit.example/gone (404)",
        "https://audit.example/sitemap.xml lists https://audit.example/ok (200)",
        "https://audit.example/sitemap.xml URL was not fetched as a page",
    ),
    rule!(
        "https.www_resolve",
        "WWW resolve issue",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Https,
        &["dns", "http_status", "redirect_chain"],
        "Apex and www hosts of the configured origin",
        thr(
            "www_consistency",
            None,
            true,
            "Do not infer a private www-vs-apex policy. Configurable preferred host.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls"],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://www.audit.example/ and https://audit.example/ fail to resolve to one preferred host",
        "https://www.audit.example/ redirects to the configured https://audit.example/",
        "https://audit.example/ apex DNS lookup was not attempted",
    ),
    rule!(
        "meta.missing_viewport",
        "Missing viewport tag",
        Severity::Error,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "viewport"],
        "Crawled HTML pages",
        thr(
            "presence",
            Some("meta name=viewport"),
            false,
            "Absence of the viewport meta tag.",
        ),
        &[MDN_VIEWPORT],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/desktop has no viewport meta",
        "https://audit.example/mobile has a viewport meta",
        "https://audit.example/partial HTML head was not stored",
    ),
    rule!(
        "meta.oversized_html",
        "Oversized HTML",
        Severity::Error,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html_bytes"],
        "Crawled HTML pages",
        thr(
            "max_html_bytes",
            None,
            true,
            "Configurable byte cap. Do not infer a private Semrush size.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML"],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/huge HTML exceeds the configured byte cap",
        "https://audit.example/ok HTML is under the configured byte cap",
        "https://audit.example/ok has no recorded body length",
    ),
    rule!(
        "amp.missing_canonical",
        "AMP missing canonical",
        Severity::Error,
        InventoryUnit::AmpPage,
        Stage::Amp,
        &["html", "amp_marker", "canonical"],
        "Pages that identify as AMP; non-AMP pages are not-applicable",
        thr(
            "amp_canonical",
            Some("AMP page has rel=canonical"),
            false,
            "Known AMP entry only.",
        ),
        &["https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery/"],
        &["TC-479"],
        RuleStatus::Specified,
        count(0, InventoryUnit::AmpPage),
        false,
        "Zero AMP pages is not an active failure. Other AMP checks are not reconstructed.",
        "https://audit.example/amp has amp marker and no canonical",
        "https://audit.example/amp has amp marker and a canonical",
        "https://audit.example/amp HTML was not stored so AMP cannot be confirmed",
    ),
    rule!(
        "hreflang.values_invalid",
        "Hreflang values invalid",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Hreflang,
        &["hreflang"],
        "Pages or headers that declare hreflang",
        thr(
            "hreflang_value",
            Some("BCP 47 or x-default"),
            false,
            "Invalid language/region tag.",
        ),
        &[GOOGLE_HREFLANG, "https://www.rfc-editor.org/rfc/rfc5646"],
        &["TC-465"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/es uses hreflang=espanol",
        "https://audit.example/es uses hreflang=es-ES",
        "https://audit.example/es link headers were not stored",
    ),
    rule!(
        "hreflang.source_conflicts",
        "Hreflang conflicts in source",
        Severity::Error,
        InventoryUnit::Conflict,
        Stage::Hreflang,
        &["hreflang"],
        "Pages that declare multiple hreflang sources",
        thr(
            "source_conflict",
            Some("conflicting targets for one language"),
            false,
            "Same language mapped to different URLs in one source.",
        ),
        &[GOOGLE_HREFLANG],
        &["TC-465"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Conflict),
        false,
        "",
        "https://audit.example/es declares two different targets for es-ES",
        "https://audit.example/es declares one target per language",
        "https://audit.example/es hreflang set is incomplete",
    ),
    rule!(
        "hreflang.incorrect_links",
        "Incorrect hreflang links",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Hreflang,
        &["hreflang", "target_http_status"],
        "Hreflang target URLs",
        thr(
            "target_ok",
            Some("target is crawlable and reciprocal as implemented in TC-465"),
            false,
            "",
        ),
        &[GOOGLE_HREFLANG],
        &["TC-465"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/es points hreflang at https://audit.example/missing",
        "https://audit.example/es points hreflang at a live reciprocal URL",
        "https://audit.example/es hreflang target was not fetched",
    ),
    rule!(
        "https.non_secure_pages",
        "Non-secure pages",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Https,
        &["url_scheme"],
        "In-scope page URLs",
        thr("scheme", Some("https"), false, "http:// page URL."),
        &["https://w3c.github.io/webappsec-secure-contexts/"],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "http://audit.example/insecure is an in-scope page",
        "https://audit.example/ok is HTTPS",
        "https://audit.example/queued has no recorded scheme after redirects",
    ),
    rule!(
        "https.certificate_expiry",
        "Expiring/expired certificate",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Https,
        &["tls_certificate"],
        "TLS hosts contacted",
        thr(
            "days_before_expiry",
            None,
            true,
            "Configurable warning window. Do not infer a private day count.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc5280"],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/ presents a certificate that is expired",
        "https://audit.example/ presents a certificate valid beyond the configured window",
        "https://audit.example/ TLS certificate was not inspected",
    ),
    rule!(
        "tls.old_protocol",
        "Old security protocol",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Tls,
        &["tls_protocol"],
        "TLS hosts contacted",
        thr(
            "min_protocol",
            None,
            true,
            "Configurable minimum (planned default TLS 1.2). Specialist diagnostics in TC-475.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc8446"],
        &["TC-475"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/ negotiates TLS 1.0",
        "https://audit.example/ negotiates TLS 1.2 or newer",
        "https://audit.example/ protocol version was not recorded",
    ),
    rule!(
        "https.certificate_name",
        "Incorrect certificate name",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Https,
        &["tls_certificate", "hostname"],
        "TLS hosts contacted",
        thr(
            "name_match",
            Some("hostname matches SAN/CN"),
            false,
            "Name mismatch.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc6125"],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/ certificate SAN does not include audit.example",
        "https://audit.example/ certificate SAN includes audit.example",
        "https://audit.example/ certificate was not stored",
    ),
    rule!(
        "https.mixed_content",
        "Mixed content",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Https,
        &["page_scheme", "resource_url"],
        "HTTPS HTML pages",
        thr(
            "mixed",
            Some("https page loads http subresource"),
            false,
            "Active or passive mixed content.",
        ),
        &[MIXED_CONTENT],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/secure loads http://audit.example/script.js",
        "https://audit.example/secure loads only https subresources",
        "https://audit.example/secure HTML was not stored",
    ),
    rule!(
        "https.homepage_http_no_redirect",
        "No HTTP-homepage redirect/canonical to HTTPS",
        Severity::Error,
        InventoryUnit::Site,
        Stage::Https,
        &["homepage_http_fetch", "redirect_chain", "canonical"],
        "Site homepage",
        thr(
            "http_homepage_to_https",
            Some("HTTP homepage redirects or canonicalizes to HTTPS"),
            false,
            "No-count site check; not a live failure.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls"],
        &["TC-468"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "http://audit.example/ stays on HTTP with no HTTPS canonical",
        "http://audit.example/ redirects to https://audit.example/",
        "http://audit.example/ was not fetched",
    ),
    rule!(
        "links.redirect_chains_loops",
        "Redirect chains and loops",
        Severity::Error,
        InventoryUnit::Url,
        Stage::Links,
        &["redirect_chain"],
        "Fetched URLs",
        thr(
            "max_redirects",
            None,
            true,
            "Configurable hop cap. Loops are always findings. Do not infer Semrush hop count.",
        ),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Url),
        false,
        "Captured value was a bare 0 with no unit.",
        "https://audit.example/a redirects to https://audit.example/b which redirects back to /a",
        "https://audit.example/ok returns 200 with no redirects",
        "https://audit.example/a Location target was not followed",
    ),
    rule!(
        "canonical.broken",
        "Broken canonical",
        Severity::Error,
        InventoryUnit::Page,
        Stage::CanonicalIndexability,
        &["canonical", "target_http_status"],
        "HTML pages that declare a canonical",
        thr(
            "canonical_target",
            Some("canonical URL is fetchable"),
            false,
            "",
        ),
        &[GOOGLE_CANONICAL],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p canonical points at https://audit.example/missing (404)",
        "https://audit.example/p canonical points at a 200 URL",
        "https://audit.example/p canonical target was not fetched",
    ),
    rule!(
        "canonical.multiple",
        "Multiple canonicals",
        Severity::Error,
        InventoryUnit::Page,
        Stage::CanonicalIndexability,
        &["canonical"],
        "Crawled HTML pages",
        thr(
            "canonical_count",
            Some("at most one distinct canonical"),
            false,
            "",
        ),
        &[GOOGLE_CANONICAL],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has two distinct rel=canonical hrefs",
        "https://audit.example/p has one canonical",
        "https://audit.example/p head was not stored",
    ),
    rule!(
        "links.meta_refresh",
        "Meta refresh",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Links,
        &["html", "meta_refresh"],
        "Crawled HTML pages",
        thr(
            "presence",
            Some("no http-equiv=refresh"),
            false,
            "Any meta refresh is a finding.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/old uses meta http-equiv=refresh",
        "https://audit.example/ok has no meta refresh",
        "https://audit.example/old HTML was not stored",
    ),
    rule!(
        "resources.broken_internal_js_css",
        "Broken internal JS/CSS",
        Severity::Error,
        InventoryUnit::Issue,
        Stage::Resources,
        &["script_src", "link_href", "resource_http_status"],
        "Same-origin script and stylesheet URLs",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "",
        ),
        &[RFC_9110],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/page references https://audit.example/gone.css (404)",
        "https://audit.example/page references https://audit.example/ok.css (200)",
        "https://audit.example/page stylesheet URL was not fetched",
    ),
    rule!(
        "tls.insecure_encryption",
        "Insecure encryption algorithms",
        Severity::Error,
        InventoryUnit::Subdomain,
        Stage::Tls,
        &["tls_cipher"],
        "TLS hosts contacted",
        thr(
            "allowed_ciphers",
            None,
            true,
            "Configurable cipher policy. Specialist diagnostics in TC-475.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc8446"],
        &["TC-475"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Subdomain),
        false,
        "",
        "https://shop.audit.example/ negotiates a known-insecure cipher",
        "https://audit.example/ negotiates an allowed cipher",
        "https://audit.example/ cipher suite was not recorded",
    ),
    rule!(
        "sitemap.oversized",
        "Oversized sitemap",
        Severity::Error,
        InventoryUnit::File,
        Stage::Sitemap,
        &["sitemap_xml", "sitemap_bytes", "sitemap_url_count"],
        "Sitemap files",
        thr(
            "sitemaps_org_limits",
            Some("50000 URLs or 50MiB uncompressed"),
            false,
            "sitemaps.org protocol limits, not a Semrush formula.",
        ),
        &[SITEMAPS],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::File),
        false,
        "",
        "https://audit.example/sitemap.xml lists more than 50000 URLs",
        "https://audit.example/sitemap.xml is under protocol limits",
        "https://audit.example/sitemap.xml size was not recorded",
    ),
    rule!(
        "url.malformed_link",
        "Malformed link URLs",
        Severity::Error,
        InventoryUnit::Link,
        Stage::UrlIdentity,
        &["anchor_href"],
        "Discovered <a href> values",
        thr(
            "url_parse",
            Some("invalid per WHATWG URL parser"),
            false,
            "",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-451", "TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from contains href=http://[broken",
        "https://audit.example/from contains only parseable hrefs",
        "https://audit.example/from HTML was not stored",
    ),
    rule!(
        "structured_data.invalid",
        "Invalid structured data",
        Severity::Error,
        InventoryUnit::Item,
        Stage::StructuredData,
        &["json_ld", "microdata"],
        "Pages with structured data blocks",
        thr(
            "schema_validity",
            None,
            true,
            "Coverage and e-commerce types are owned by TC-467. Do not infer a private validator set.",
        ),
        &[SCHEMA_ORG],
        &["TC-467"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Item),
        false,
        "",
        "https://audit.example/product JSON-LD is not valid JSON",
        "https://audit.example/product JSON-LD parses as a Product",
        "https://audit.example/product HTML was not stored",
    ),
    rule!(
        "meta.missing_viewport_width",
        "Missing viewport width",
        Severity::Error,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "viewport"],
        "Pages that have a viewport tag",
        thr(
            "viewport_width",
            Some("width directive present"),
            false,
            "Viewport exists but width is missing. Pages without viewport are not-applicable here.",
        ),
        &[MDN_VIEWPORT],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p viewport is content=initial-scale=1 with no width",
        "https://audit.example/p viewport includes width=device-width",
        "https://audit.example/p viewport content string was not stored",
    ),
    rule!(
        "performance.slow_load",
        "Slow load speed",
        Severity::Error,
        InventoryUnit::Page,
        Stage::Performance,
        &["ttfb_or_total_time"],
        "Fetched pages",
        thr(
            "max_load_ms",
            None,
            true,
            "Configurable measured timing. Do not infer a private Semrush speed formula.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/Performance"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/slow exceeds the configured load budget",
        "https://audit.example/ok is within the configured load budget",
        "https://audit.example/ok has no recorded timings",
    ),
    rule!(
        "meta.long_title",
        "Long title",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "title"],
        "Crawled HTML pages with a title",
        thr(
            "max_title_chars",
            None,
            true,
            "Configurable character cap. Do not infer a private Semrush pixel or character formula.",
        ),
        &[MDN_TITLE],
        &["TC-458"],
        RuleStatus::Specified,
        count(73, InventoryUnit::Page),
        false,
        "Current 14 September 2026 baseline finding. 78 'new issues' is a separate historical column.",
        "https://audit.example/long title exceeds the configured character cap",
        "https://audit.example/ok title is within the configured character cap",
        "https://audit.example/ok title text was not stored",
    ),
    rule!(
        "links.broken_external",
        "Broken external links",
        Severity::Warning,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_href", "target_http_status", "origin"],
        "Cross-origin <a href> targets",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "",
        ),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from links to https://ext.audit.example/missing (404)",
        "https://audit.example/from links to https://ext.audit.example/ok (200)",
        "https://audit.example/from external target was not fetched",
    ),
    rule!(
        "images.broken_external",
        "Broken external images",
        Severity::Warning,
        InventoryUnit::Image,
        Stage::Images,
        &["img_src", "resource_http_status"],
        "Cross-origin img resources",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "",
        ),
        &[RFC_9110],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Image),
        false,
        "",
        "https://audit.example/page references https://cdn.audit.example/gone.png (404)",
        "https://audit.example/page references https://cdn.audit.example/ok.png (200)",
        "https://audit.example/page external image was not fetched",
    ),
    rule!(
        "https.https_links_to_http",
        "HTTPS page links to HTTP",
        Severity::Warning,
        InventoryUnit::Link,
        Stage::Https,
        &["page_scheme", "anchor_href"],
        "HTTPS HTML pages",
        thr(
            "https_to_http_link",
            Some("https page has http href"),
            false,
            "Navigation mixed scheme.",
        ),
        &[MIXED_CONTENT],
        &["TC-468"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/secure links to http://audit.example/other",
        "https://audit.example/secure links only to https URLs",
        "https://audit.example/secure HTML was not stored",
    ),
    rule!(
        "meta.short_title",
        "Short title",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "title"],
        "Crawled HTML pages with a title",
        thr(
            "min_title_chars",
            None,
            true,
            "Configurable minimum. Do not infer a private Semrush character formula.",
        ),
        &[MDN_TITLE],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/x title is below the configured minimum",
        "https://audit.example/ok title meets the configured minimum",
        "https://audit.example/ok title text was not stored",
    ),
    rule!(
        "heading.missing_h1",
        "Missing H1",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "h1"],
        "Crawled HTML pages",
        thr(
            "h1_count",
            Some("at least one h1"),
            false,
            "No universal SEO benefit is asserted.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements"],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has no h1",
        "https://audit.example/p has one h1",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "heading.h1_matches_title",
        "Matching H1 and title",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "h1", "title"],
        "Pages with both title and h1",
        thr(
            "normalized_equality",
            Some("trim and collapse whitespace"),
            false,
            "Exact match after normalization. No universal SEO benefit is asserted.",
        ),
        &[MDN_TITLE],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p title and h1 are identical after normalization",
        "https://audit.example/p title and h1 differ",
        "https://audit.example/p is missing stored h1 or title text",
    ),
    rule!(
        "meta.missing_description",
        "Missing description",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "meta_description"],
        "Crawled HTML pages",
        thr("presence", Some("non-empty meta description"), false, ""),
        &[MDN_META],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has no meta description",
        "https://audit.example/p has a non-empty meta description",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "links.too_many_on_page",
        "Too many on-page links",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Links,
        &["anchor_href"],
        "Crawled HTML pages",
        thr(
            "max_on_page_links",
            None,
            true,
            "Configurable count. Do not infer a private Semrush cap.",
        ),
        &["https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/hub exceeds the configured on-page link cap",
        "https://audit.example/ok is within the configured on-page link cap",
        "https://audit.example/ok HTML was not stored",
    ),
    rule!(
        "links.temporary_redirect",
        "Temporary redirect",
        Severity::Warning,
        InventoryUnit::Url,
        Stage::Links,
        &["http_status", "redirect_chain"],
        "Fetched URLs",
        thr(
            "status",
            Some("302/307"),
            false,
            "Temporary redirect class.",
        ),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Url),
        false,
        "",
        "https://audit.example/old returns HTTP 302",
        "https://audit.example/ok returns HTTP 200",
        "https://audit.example/old has no recorded status",
    ),
    rule!(
        "images.missing_alt",
        "Missing image alt attribute",
        Severity::Warning,
        InventoryUnit::Image,
        Stage::Images,
        &["img_alt"],
        "img elements in HTML",
        thr(
            "alt_attribute",
            Some("alt attribute present"),
            false,
            "Empty alt may be intentional; TC-462 decides.",
        ),
        &["https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element"],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Image),
        false,
        "",
        "https://audit.example/p has <img src=https://audit.example/a.png> without alt",
        "https://audit.example/p images include an alt attribute",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "content.low_text_html_ratio",
        "Low text/HTML ratio",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Content,
        &["html_bytes", "text_extract"],
        "Crawled HTML pages",
        thr(
            "min_text_html_ratio",
            None,
            true,
            "Do not infer a private Semrush ratio. Explainable assessment in TC-476.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "AI/content heuristic. Historical 'new issues' 260 is not a current count.",
        "https://audit.example/thin has extracted text below the configured ratio",
        "https://audit.example/ok meets the configured ratio",
        "https://audit.example/ok has no extracted text",
    ),
    rule!(
        "url.too_many_parameters",
        "Too many URL parameters",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Links,
        &["url"],
        "Page URLs",
        thr(
            "max_query_params",
            None,
            true,
            "Configurable count. Do not infer a private Semrush cap.",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p?a=1&b=2&c=3 exceeds the configured parameter cap",
        "https://audit.example/p has no query string",
        "https://audit.example/p raw URL was not stored",
    ),
    rule!(
        "hreflang.missing_hreflang_and_lang",
        "No hreflang and lang attributes",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Hreflang,
        &["html_lang", "hreflang"],
        "Crawled HTML pages",
        thr(
            "presence",
            Some("html lang or hreflang present"),
            false,
            "Both absent.",
        ),
        &[
            GOOGLE_HREFLANG,
            "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang",
        ],
        &["TC-465"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has neither html lang nor hreflang",
        "https://audit.example/p has html lang=es",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "meta.missing_charset",
        "Missing character encoding",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "charset"],
        "Crawled HTML pages",
        thr(
            "presence",
            Some("meta charset or Content-Type charset"),
            false,
            "",
        ),
        &["https://html.spec.whatwg.org/multipage/parsing.html#determining-the-character-encoding"],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has no charset declaration",
        "https://audit.example/p has meta charset=utf-8",
        "https://audit.example/p headers and HTML were not stored",
    ),
    rule!(
        "meta.missing_doctype",
        "Missing doctype",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "doctype"],
        "Crawled HTML pages",
        thr("presence", Some("<!DOCTYPE html>"), false, ""),
        &["https://html.spec.whatwg.org/multipage/syntax.html#the-doctype"],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p starts with <html> and no doctype",
        "https://audit.example/p starts with <!DOCTYPE html>",
        "https://audit.example/p leading bytes were not stored",
    ),
    rule!(
        "content.low_word_count",
        "Low word count",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Content,
        &["text_extract"],
        "Crawled HTML pages",
        thr(
            "min_words",
            None,
            true,
            "Do not infer a private Semrush word floor. Explainable assessment in TC-476.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "AI/content heuristic.",
        "https://audit.example/thin extracted text is below the configured word floor",
        "https://audit.example/ok meets the configured word floor",
        "https://audit.example/ok has no extracted text",
    ),
    rule!(
        "meta.incompatible_plugin_content",
        "Incompatible plugin content",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "embed_object_applet"],
        "Crawled HTML pages",
        thr(
            "legacy_plugin",
            Some("no embed/object/applet plugin content"),
            false,
            "Legacy format.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object"],
        &["TC-458"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "Legacy plugin markup. Deferred with other legacy format checks.",
        "https://audit.example/flash embeds a plugin object",
        "https://audit.example/ok has no plugin embed",
        "https://audit.example/flash HTML was not stored",
    ),
    rule!(
        "meta.frames",
        "Frames",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "frameset_or_frame"],
        "Crawled HTML pages",
        thr(
            "frames",
            Some("no frameset/frame"),
            false,
            "Legacy frames. iframe is out of this label until researched.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame"],
        &["TC-458"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "Legacy frameset markup.",
        "https://audit.example/legacy uses frameset/frame",
        "https://audit.example/ok has no frameset",
        "https://audit.example/legacy HTML was not stored",
    ),
    rule!(
        "url.underscores",
        "URL underscores",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Links,
        &["url"],
        "Page URL paths",
        thr(
            "underscore",
            Some("no _ in path"),
            false,
            "Heuristic only. No universal SEO benefit is asserted.",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/foo_bar contains an underscore in the path",
        "https://audit.example/foo-bar has no underscore in the path",
        "https://audit.example/foo raw path was not stored",
    ),
    rule!(
        "links.internal_outgoing_nofollow",
        "Internal outgoing nofollow",
        Severity::Warning,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_rel", "origin"],
        "Same-origin <a> links",
        thr(
            "rel_nofollow",
            Some("internal link without nofollow"),
            false,
            "",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/nofollow"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from has rel=nofollow to https://audit.example/to",
        "https://audit.example/from internal links omit nofollow",
        "https://audit.example/from HTML was not stored",
    ),
    rule!(
        "sitemap.not_declared_in_robots",
        "Sitemap not declared in robots",
        Severity::Warning,
        InventoryUnit::Site,
        Stage::Sitemap,
        &["robots_txt", "sitemap_url"],
        "Origin robots.txt",
        thr(
            "robots_sitemap",
            Some("Sitemap: directive present"),
            false,
            "No-count site check; not a live failure.",
        ),
        &[RFC_9309, SITEMAPS],
        &["TC-460"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "https://audit.example/robots.txt has no Sitemap directive",
        "https://audit.example/robots.txt declares Sitemap: https://audit.example/sitemap.xml",
        "https://audit.example/robots.txt was not fetched",
    ),
    rule!(
        "sitemap.not_found",
        "Sitemap not found",
        Severity::Warning,
        InventoryUnit::Site,
        Stage::Sitemap,
        &["sitemap_http_status"],
        "Expected sitemap URL",
        thr(
            "sitemap_fetch",
            Some("sitemap reachable"),
            false,
            "No-count site check; not a live failure.",
        ),
        &[SITEMAPS],
        &["TC-460"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "https://audit.example/sitemap.xml returns 404",
        "https://audit.example/sitemap.xml returns 200",
        "https://audit.example/sitemap.xml was not requested",
    ),
    rule!(
        "https.homepage_not_https",
        "Homepage does not use HTTPS",
        Severity::Warning,
        InventoryUnit::Site,
        Stage::Https,
        &["start_url"],
        "Configured homepage",
        thr(
            "scheme",
            Some("https"),
            false,
            "No-count site check; not a live failure.",
        ),
        &["https://w3c.github.io/webappsec-secure-contexts/"],
        &["TC-468"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "http://audit.example/ is the configured homepage",
        "https://audit.example/ is the configured homepage",
        "https://audit.example/ start URL was not recorded",
    ),
    rule!(
        "tls.no_sni",
        "No SNI support",
        Severity::Warning,
        InventoryUnit::Subdomain,
        Stage::Tls,
        &["tls_sni"],
        "TLS hosts contacted",
        thr(
            "sni",
            Some("SNI presented and accepted"),
            false,
            "Specialist diagnostics in TC-475.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc6066"],
        &["TC-475"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Subdomain),
        false,
        "",
        "https://shop.audit.example/ handshake fails when SNI is required",
        "https://audit.example/ handshake succeeds with SNI",
        "https://audit.example/ SNI outcome was not recorded",
    ),
    rule!(
        "sitemap.http_urls_in_https",
        "HTTP URLs in HTTPS sitemap",
        Severity::Warning,
        InventoryUnit::Url,
        Stage::Sitemap,
        &["sitemap_xml"],
        "HTTPS sitemap files",
        thr("sitemap_url_scheme", Some("https loc"), false, ""),
        &[SITEMAPS],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Url),
        false,
        "",
        "https://audit.example/sitemap.xml lists http://audit.example/p",
        "https://audit.example/sitemap.xml lists only https loc values",
        "https://audit.example/sitemap.xml body was not stored",
    ),
    rule!(
        "performance.uncompressed_pages",
        "Uncompressed pages",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Performance,
        &["content_encoding"],
        "Fetched HTML pages",
        thr("content_encoding", Some("gzip or br"), false, ""),
        &["https://www.rfc-editor.org/rfc/rfc9110#name-content-encoding"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has no Content-Encoding",
        "https://audit.example/p is served with Content-Encoding: gzip",
        "https://audit.example/p response headers were not stored",
    ),
    rule!(
        "resources.blocked_internal_robots",
        "Blocked internal resources in robots",
        Severity::Warning,
        InventoryUnit::Issue,
        Stage::Resources,
        &["resource_url", "robots_txt"],
        "Same-origin page resources",
        thr(
            "robots_disallow",
            Some("resource allowed for the crawl UA"),
            false,
            "",
        ),
        &[RFC_9309],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/app.js is disallowed by https://audit.example/robots.txt",
        "https://audit.example/app.js is allowed by robots.txt",
        "https://audit.example/robots.txt was not stored",
    ),
    rule!(
        "performance.uncompressed_js_css",
        "Uncompressed JS/CSS",
        Severity::Warning,
        InventoryUnit::Issue,
        Stage::Performance,
        &["content_encoding", "resource_url"],
        "JS and CSS resources",
        thr("content_encoding", Some("gzip or br"), false, ""),
        &["https://www.rfc-editor.org/rfc/rfc9110#name-content-encoding"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/app.js has no Content-Encoding",
        "https://audit.example/app.js is served gzip-encoded",
        "https://audit.example/app.js headers were not stored",
    ),
    rule!(
        "performance.uncached_js_css",
        "Uncached JS/CSS",
        Severity::Warning,
        InventoryUnit::Issue,
        Stage::Performance,
        &["cache_control", "resource_url"],
        "JS and CSS resources",
        thr(
            "cacheability",
            None,
            true,
            "Configurable cache lifetime. Do not infer a private Semrush rule.",
        ),
        &["https://www.rfc-editor.org/rfc/rfc9111"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/app.js is Cache-Control: no-store",
        "https://audit.example/app.js is Cache-Control: max-age=86400",
        "https://audit.example/app.js cache headers were not stored",
    ),
    rule!(
        "performance.js_css_total_size",
        "JS/CSS total size too large",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Performance,
        &["resource_bytes"],
        "HTML pages with script/style resources",
        thr(
            "max_js_css_bytes",
            None,
            true,
            "Configurable budget. Do not infer a private Semrush size.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/Performance"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/heavy JS+CSS bytes exceed the configured budget",
        "https://audit.example/ok JS+CSS bytes are within the configured budget",
        "https://audit.example/ok resource sizes were not stored",
    ),
    rule!(
        "performance.too_many_js_css_files",
        "Too many JS/CSS files",
        Severity::Warning,
        InventoryUnit::Page,
        Stage::Performance,
        &["script_src", "link_href"],
        "HTML pages",
        thr(
            "max_js_css_files",
            None,
            true,
            "Configurable count. Do not infer a private Semrush cap.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/Performance"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/heavy exceeds the configured JS/CSS file cap",
        "https://audit.example/ok is within the configured JS/CSS file cap",
        "https://audit.example/ok resource list was not stored",
    ),
    rule!(
        "performance.unminified_js_css",
        "Unminified JS/CSS",
        Severity::Warning,
        InventoryUnit::Issue,
        Stage::Performance,
        &["resource_body"],
        "JS and CSS resources",
        thr(
            "minification_heuristic",
            None,
            true,
            "Explainable whitespace/comment heuristic only. Do not infer a private Semrush detector.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Learn/Performance"],
        &["TC-473"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/app.js contains large runs of whitespace and comments",
        "https://audit.example/app.min.js meets the configured minification heuristic",
        "https://audit.example/app.js body was not stored",
    ),
    rule!(
        "links.url_too_long",
        "Link URLs too long",
        Severity::Warning,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_href"],
        "Discovered links",
        thr(
            "max_link_chars",
            None,
            true,
            "Configurable length. Do not infer a private Semrush cap.",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from has an href longer than the configured cap",
        "https://audit.example/from hrefs are within the configured cap",
        "https://audit.example/from HTML was not stored",
    ),
    rule!(
        "resources.blocked_external_robots",
        "Blocked external resources in robots",
        Severity::Notice,
        InventoryUnit::Issue,
        Stage::Resources,
        &["resource_url", "external_robots_txt"],
        "Cross-origin page resources",
        thr(
            "robots_disallow",
            Some("external resource allowed"),
            false,
            "",
        ),
        &[RFC_9309],
        &["TC-462"],
        RuleStatus::Specified,
        count(433, InventoryUnit::Issue),
        false,
        "Current 14 September 2026 baseline finding.",
        "https://audit.example/p loads https://cdn.audit.example/x.js disallowed by that origin robots.txt",
        "https://audit.example/p external resources are allowed by their robots.txt",
        "https://cdn.audit.example/robots.txt was not fetched",
    ),
    rule!(
        "crawl.depth_gt_3",
        "Depth greater than 3 clicks",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Crawl,
        &["link_depth"],
        "Pages discovered from the homepage",
        thr(
            "max_clicks",
            Some("3"),
            false,
            "Homepage-based click depth stated in the inventory. Not catalogue size.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/links-crawlable"],
        &["TC-461"],
        RuleStatus::Specified,
        count(302, InventoryUnit::Page),
        false,
        "Current 14 September 2026 baseline finding.",
        "https://audit.example/deep is 4 clicks from https://audit.example/",
        "https://audit.example/ok is 2 clicks from https://audit.example/",
        "https://audit.example/ok has no recorded inbound path from the homepage",
    ),
    rule!(
        "links.resources_as_page_link",
        "Resources formatted as page link",
        Severity::Notice,
        InventoryUnit::Resource,
        Stage::Links,
        &["anchor_href"],
        "URLs used as <a href>",
        thr(
            "resource_as_anchor",
            None,
            true,
            "Do not infer a private Semrush resource-vs-page classifier.",
        ),
        &["https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element"],
        &["TC-459"],
        RuleStatus::Specified,
        count(9, InventoryUnit::Resource),
        true,
        "Transcribed label only. Do not infer a private Semrush resource-vs-page classifier. Optional Crawlytic heuristic: an <a href> whose path looks like a static resource (js, css, image, font, pdf). Research required before claiming parity. No universal SEO benefit is asserted.",
        "https://audit.example/p uses <a href=https://audit.example/app.js>",
        "https://audit.example/p anchors point at HTML pages",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "content.optimization_required",
        "Content optimization required",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Ai,
        &["text_extract"],
        "Crawled HTML pages",
        thr(
            "explainable_content_score",
            None,
            true,
            "Do not infer a private Semrush content-score formula.",
        ),
        &["https://developers.google.com/search/docs/fundamentals/creating-helpful-content"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(4, InventoryUnit::Page),
        true,
        "Transcribed label only. Do not infer a private Semrush content-score formula. Current baseline count 4 is historical observation, not a live checker. Explainable features belong in TC-476. No universal SEO benefit is asserted.",
        "https://audit.example/thin is flagged by the TC-476 explainable heuristic once defined",
        "https://audit.example/ok is not flagged by that heuristic",
        "https://audit.example/ok has no extracted text",
    ),
    rule!(
        "url.longer_than_200",
        "Page URL longer than 200 characters",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Links,
        &["url"],
        "Page URLs",
        thr(
            "max_url_chars",
            Some("200"),
            false,
            "Threshold stated in the inventory.",
        ),
        &["https://url.spec.whatwg.org/"],
        &["TC-459"],
        RuleStatus::Specified,
        count(3, InventoryUnit::Page),
        false,
        "Current 14 September 2026 baseline finding.",
        "https://audit.example/this-url-is-intentionally-longer-than-two-hundred-characters-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "https://audit.example/short is at most 200 characters",
        "https://audit.example/p raw URL was not stored",
    ),
    rule!(
        "links.non_descriptive_anchors",
        "Non-descriptive anchors",
        Severity::Notice,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_text"],
        "<a> elements with href",
        thr(
            "descriptive_anchor",
            None,
            true,
            "Configurable stop-list (click here, more, etc.). Do not infer a private Semrush list.",
        ),
        &["https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html"],
        &["TC-459"],
        RuleStatus::Specified,
        count(3, InventoryUnit::Link),
        false,
        "Current 14 September 2026 baseline finding.",
        "https://audit.example/p has anchor text click here to https://audit.example/to",
        "https://audit.example/p anchors describe their targets",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "heading.multiple_h1",
        "Multiple H1",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::HtmlMetadata,
        &["html", "h1"],
        "Crawled HTML pages",
        thr(
            "h1_count",
            Some("at most one h1"),
            false,
            "No universal SEO benefit is asserted.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements"],
        &["TC-458"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has two h1 elements",
        "https://audit.example/p has one h1",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "ai.llms_txt_missing",
        "llms.txt missing",
        Severity::Notice,
        InventoryUnit::Site,
        Stage::Ai,
        &["llms_txt"],
        "Origin well-known llms.txt",
        thr(
            "presence",
            Some("llms.txt reachable"),
            false,
            "No-count site check; not a live failure. Optional AI file.",
        ),
        &[LLMS_TXT],
        &["TC-476"],
        RuleStatus::Deferred,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure. Optional AI milestone.",
        "https://audit.example/llms.txt returns 404",
        "https://audit.example/llms.txt returns 200",
        "https://audit.example/llms.txt was not requested",
    ),
    rule!(
        "robots.pages_blocked_from_crawling",
        "Pages blocked from crawling",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Robots,
        &["url", "robots_txt", "meta_robots"],
        "Discovered in-scope URLs",
        thr("robots_disallow", Some("URL allowed"), false, ""),
        &[RFC_9309, GOOGLE_ROBOTS],
        &["TC-450", "TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/private is disallowed by robots.txt",
        "https://audit.example/ok is allowed by robots.txt",
        "https://audit.example/robots.txt was not stored",
    ),
    rule!(
        "links.external_outgoing_nofollow",
        "External outgoing nofollow",
        Severity::Notice,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_rel", "origin"],
        "Cross-origin <a> links",
        thr(
            "rel_nofollow",
            Some("recorded, not a defect by default"),
            false,
            "Informational. No universal SEO benefit is asserted.",
        ),
        &["https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/nofollow"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from has rel=nofollow to https://ext.audit.example/",
        "https://audit.example/from external links omit nofollow",
        "https://audit.example/from HTML was not stored",
    ),
    rule!(
        "robots.not_found",
        "Robots not found",
        Severity::Notice,
        InventoryUnit::Site,
        Stage::Robots,
        &["robots_http_status"],
        "Origin robots.txt",
        thr(
            "robots_fetch",
            Some("robots.txt reachable"),
            false,
            "No-count site check; not a live failure. Missing robots is not a defect.",
        ),
        &[RFC_9309],
        &["TC-460"],
        RuleStatus::Specified,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure.",
        "https://audit.example/robots.txt returns 404",
        "https://audit.example/robots.txt returns 200",
        "https://audit.example/robots.txt was not requested",
    ),
    rule!(
        "hreflang.language_mismatch",
        "Hreflang language mismatch",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Hreflang,
        &["hreflang", "html_lang", "text_language"],
        "Pages that declare language",
        thr(
            "language_agreement",
            None,
            true,
            "Do not infer a private Semrush language-detection formula.",
        ),
        &[GOOGLE_HREFLANG],
        &["TC-465"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        true,
        "Transcribed label only. Research required: compare hreflang, html lang, and detectable content language. No universal SEO benefit is asserted.",
        "https://audit.example/es declares hreflang=es while html lang=en",
        "https://audit.example/es hreflang and html lang agree",
        "https://audit.example/es language signals were not stored",
    ),
    rule!(
        "tls.no_hsts",
        "No HSTS",
        Severity::Notice,
        InventoryUnit::Subdomain,
        Stage::Tls,
        &["strict_transport_security"],
        "TLS hosts contacted",
        thr(
            "hsts",
            Some("Strict-Transport-Security present"),
            false,
            "Specialist diagnostics in TC-475.",
        ),
        &[RFC_6797],
        &["TC-475"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Subdomain),
        false,
        "",
        "https://shop.audit.example/ omits Strict-Transport-Security",
        "https://audit.example/ sends Strict-Transport-Security",
        "https://audit.example/ response headers were not stored",
    ),
    rule!(
        "analytics.orphans_in_ga",
        "Orphans in Google Analytics",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Analytics,
        &["ga_url_list", "crawl_url_list"],
        "URLs present in connected Analytics evidence",
        thr(
            "in_crawl",
            Some("Analytics URL also crawled or excluded with reason"),
            false,
            "Requires TC-477. Never store credentials in fixtures.",
        ),
        &["https://developers.google.com/analytics"],
        &["TC-477"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "External evidence. Optional until Search Console/Analytics integration.",
        "https://audit.example/orphan appears in Analytics fixtures but not in the crawl set",
        "https://audit.example/ok appears in both Analytics fixtures and the crawl set",
        "https://audit.example/ analytics URL list was not supplied",
    ),
    rule!(
        "crawl.orphans_in_sitemaps",
        "Orphans in sitemaps",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Crawl,
        &["sitemap_url", "link_graph"],
        "URLs listed in sitemaps",
        thr(
            "inbound_internal",
            Some("sitemap URL has internal inbound or is the homepage"),
            false,
            "",
        ),
        &[SITEMAPS],
        &["TC-461"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/orphan is in sitemap.xml with no internal inbound link",
        "https://audit.example/ok is in sitemap.xml and linked internally",
        "https://audit.example/ok sitemap membership was not stored",
    ),
    rule!(
        "indexability.x_robots_noindex",
        "X-Robots-Tag noindex",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::CanonicalIndexability,
        &["x_robots_tag"],
        "Fetched pages",
        thr(
            "noindex",
            Some("X-Robots-Tag does not include noindex"),
            false,
            "Informational indexability evidence.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag"],
        &["TC-460"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p sends X-Robots-Tag: noindex",
        "https://audit.example/p omits noindex in X-Robots-Tag",
        "https://audit.example/p headers were not stored",
    ),
    rule!(
        "resources.broken_external_js_css",
        "Broken external JS/CSS",
        Severity::Notice,
        InventoryUnit::Issue,
        Stage::Resources,
        &["script_src", "link_href", "resource_http_status"],
        "Cross-origin script and stylesheet URLs",
        thr(
            "broken_status",
            Some("4xx/5xx/DNS/connect failure"),
            false,
            "",
        ),
        &[RFC_9110],
        &["TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Issue),
        false,
        "",
        "https://audit.example/p references https://cdn.audit.example/gone.js (404)",
        "https://audit.example/p references https://cdn.audit.example/ok.js (200)",
        "https://audit.example/p external script was not fetched",
    ),
    rule!(
        "crawl.only_one_incoming_internal",
        "Only one incoming internal link",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Crawl,
        &["link_graph"],
        "Crawled pages other than the homepage",
        thr(
            "inbound_internal",
            Some("more than one inbound internal link"),
            false,
            "Homepage is not-applicable.",
        ),
        &["https://developers.google.com/search/docs/crawling-indexing/links-crawlable"],
        &["TC-461"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Page),
        false,
        "",
        "https://audit.example/p has exactly one inbound internal link",
        "https://audit.example/p has two inbound internal links",
        "https://audit.example/p inbound graph was not computed",
    ),
    rule!(
        "links.permanent_redirects",
        "Permanent redirects",
        Severity::Notice,
        InventoryUnit::Url,
        Stage::Links,
        &["http_status", "redirect_chain"],
        "Fetched URLs",
        thr("status", Some("301/308"), false, "Informational."),
        &[RFC_9110],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Url),
        false,
        "",
        "https://audit.example/old returns HTTP 301",
        "https://audit.example/ok returns HTTP 200",
        "https://audit.example/old has no recorded status",
    ),
    rule!(
        "links.missing_anchor_text",
        "Missing anchor text",
        Severity::Notice,
        InventoryUnit::Link,
        Stage::Links,
        &["anchor_text"],
        "<a> elements with href",
        thr(
            "anchor_text",
            Some("non-empty accessible name"),
            false,
            "Image-only anchors need alt; owned by TC-459.",
        ),
        &["https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html"],
        &["TC-459"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/p has an <a href=https://audit.example/to> with empty accessible name",
        "https://audit.example/p anchors have accessible names",
        "https://audit.example/p HTML was not stored",
    ),
    rule!(
        "links.external_http_403",
        "External page/resource HTTP 403",
        Severity::Notice,
        InventoryUnit::Link,
        Stage::Links,
        &["target_http_status", "origin"],
        "Cross-origin pages and resources",
        thr(
            "status",
            Some("403"),
            false,
            "Informational; may be bot-blocking.",
        ),
        &[RFC_9110],
        &["TC-459", "TC-462"],
        RuleStatus::Specified,
        count(0, InventoryUnit::Link),
        false,
        "",
        "https://audit.example/from points at https://ext.audit.example/private (403)",
        "https://audit.example/from external targets return 200",
        "https://audit.example/from external target was not fetched",
    ),
    rule!(
        "ai.llms_txt_formatting",
        "llms.txt formatting",
        Severity::Notice,
        InventoryUnit::Site,
        Stage::Ai,
        &["llms_txt"],
        "Origin llms.txt when present; missing file is not-applicable",
        thr(
            "llms_txt_syntax",
            None,
            true,
            "Formatting rules owned by TC-476. No-count site check; not a live failure.",
        ),
        &[LLMS_TXT],
        &["TC-476"],
        RuleStatus::Deferred,
        CapturedCurrent::NoCount,
        false,
        "No count does not mean failure. Optional AI milestone.",
        "https://audit.example/llms.txt exists but is not valid according to TC-476",
        "https://audit.example/llms.txt meets the TC-476 formatting rules",
        "https://audit.example/llms.txt body was not stored",
    ),
    rule!(
        "content.too_much",
        "Too much content",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Content,
        &["text_extract"],
        "Crawled HTML pages",
        thr(
            "max_words",
            None,
            true,
            "Do not infer a private Semrush word ceiling. Explainable assessment in TC-476.",
        ),
        &["https://developers.google.com/search/docs/fundamentals/creating-helpful-content"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "AI/content heuristic. No universal SEO benefit is asserted.",
        "https://audit.example/huge extracted text exceeds the configured word ceiling",
        "https://audit.example/ok is within the configured word ceiling",
        "https://audit.example/ok has no extracted text",
    ),
    rule!(
        "content.outdated",
        "Outdated content",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Content,
        &["last_modified", "visible_date"],
        "Crawled HTML pages",
        thr(
            "max_age",
            None,
            true,
            "Do not infer a private Semrush freshness formula. Explainable assessment in TC-476.",
        ),
        &["https://developers.google.com/search/docs/fundamentals/creating-helpful-content"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "AI/content heuristic.",
        "https://audit.example/old visible date is older than the configured age",
        "https://audit.example/ok visible date is within the configured age",
        "https://audit.example/ok has no stored date evidence",
    ),
    rule!(
        "content.low_semantic_html",
        "Low semantic HTML usage",
        Severity::Notice,
        InventoryUnit::Page,
        Stage::Content,
        &["html", "landmark_elements"],
        "Crawled HTML pages",
        thr(
            "semantic_html",
            None,
            true,
            "Do not infer a private Semrush semantic score. Explainable assessment in TC-476.",
        ),
        &["https://html.spec.whatwg.org/multipage/sections.html"],
        &["TC-476"],
        RuleStatus::Deferred,
        count(0, InventoryUnit::Page),
        false,
        "AI/content heuristic. No universal SEO benefit is asserted.",
        "https://audit.example/divsoup has no semantic landmarks",
        "https://audit.example/ok uses main/article/nav as defined by TC-476",
        "https://audit.example/ok HTML was not stored",
    ),
    rule!(
        "amp.hidden_catalogue",
        "AMP checks hidden by upgrade message",
        Severity::Error,
        InventoryUnit::Site,
        Stage::Amp,
        &["amp_marker"],
        "Not evaluated. AMP remainder was hidden in the source UI.",
        thr(
            "unsupported_amp_remainder",
            None,
            true,
            "Do not reconstruct undisclosed AMP checks. Deferred under TC-479.",
        ),
        &["https://amp.dev/"],
        &["TC-479"],
        RuleStatus::Deferred,
        CapturedCurrent::NoCount,
        false,
        "Limited AMP information only. This is not an active failure.",
        "https://audit.example/amp would require an unsupported AMP check that was not transcribed",
        "https://audit.example/html is not AMP so remainder checks are not-applicable",
        "https://audit.example/amp HTML was not stored",
    ),
];
